/**
 * MERIDIAN core philosophy — evidence engine, not oracle.
 * CMC provides data; MERIDIAN provides reasoning.
 * Optimize for trust over 1,000 trades, not excitement on the next trade.
 */

export type MeridianVerdict = "GRANT" | "DENY" | "WAIT" | "UNKNOWN";

export type MeridianDataQuality = "complete" | "partial" | "degraded" | "unavailable";

export const MERIDIAN_TAGLINE =
  "MERIDIAN is a world-class market intelligence operating system — not an oracle, hype machine, or signal spammer." as const;

export const MERIDIAN_NORTH_STAR =
  "Build something users voluntarily open every day because it consistently helps them make better decisions." as const;

export const MERIDIAN_PRIMARY_OBJECTIVE =
  "Help users make better decisions than they would have made alone — protect capital, improve consistency, reduce emotional trading." as const;

/** The instruction that matters more than everything else */
export const MERIDIAN_TRUST_HORIZON =
  "Optimize for trust accumulated over 1,000 trades, not excitement generated by the next trade." as const;

export const MERIDIAN_RETENTION_PRINCIPLES = [
  "Reliability over hype",
  "Truthfulness over cosmetic accuracy",
  "Consistency over random signal changes",
  "Transparency — never hide losses or drawdowns",
  "Explainability — every verdict cites evidence",
  "Accountability — autopsy every closed trade",
] as const;

export const MERIDIAN_QUALITY_RULES = [
  "Never force signals — trade only when evidence is strong",
  "WAIT is a valid answer",
  "UNKNOWN is a valid answer",
  "FLAT is a valid position — not failure",
  "No trade is better than a poor trade",
  "Less activity, higher selectivity",
  "Never claim 95% success, 99% accuracy, or guaranteed profits",
] as const;

/** MERIDIAN must never bias toward LONG, SHORT, or FLAT */
export const MERIDIAN_SIGNAL_PHILOSOPHY = {
  principle: "MERIDIAN synthesizes evidence — it does not predict.",
  directions: "LONG, SHORT, and FLAT emerge from evidence; none is preferred.",
  flat: "FLAT is a position. Professional systems spend most of their time flat.",
  activity: "Trade quality matters more than trade frequency.",
  scores:
    "Publish long, short, hold, conflict, uncertainty, and data quality scores — not forced direction.",
} as const;

/** Canonical Decision Engine principles — see docs/MERIDIAN-DECISION-ENGINE.md */
export const MERIDIAN_DECISION_ENGINE = {
  neutrality: "No preferred direction — not bullish, not bearish, not permanently flat.",
  layers: 9,
  scoring: ["longScore", "shortScore", "holdScore", "conflictScore", "uncertainty", "dataQualityScore"],
  vetoes: ["regime risk-off", "liquidity fail", "constitution DENY"],
  timeframes: "3m through 1w — higher TF anchors; micro cannot override swing alone.",
  routerTruth: "Position router is Overview ONE TRUTH; decision scores explain on Technical tab.",
  abstention: "WAIT and UNKNOWN are valid. No trade beats a low-quality trade.",
} as const;

/** Global MERIDIAN law — applies to every module, API, agent, and UI surface */
export const MERIDIAN_TRUTH_LAW =
  "Every feature must produce real value, real data, real reasoning, and real accountability — cosmetic intelligence is forbidden." as const;

export const MERIDIAN_TRUTH_FORBIDDEN = [
  "Cosmetic intelligence",
  "Fake intelligence",
  "Fabricated confidence",
  "Artificial complexity",
  "Placeholder reasoning",
  "Pretending certainty when data is missing",
  "Silent defaults that hide unavailable feeds",
] as const;

export const MERIDIAN_TRUTH_REQUIREMENTS = [
  "Real data with source, timestamp, and freshness",
  "Real reasoning traceable to skills or deterministic logic",
  "Real accountability — losses and drawdowns visible",
  "Honest DATA UNAVAILABLE when inputs are missing",
  "Evidence-derived confidence — not probability of profit",
  "LLM narration only — never invent market numbers",
] as const;

export const MERIDIAN_GOLDEN_RULES = [
  "Never hallucinate — every number must trace to a live API or deterministic skill.",
  "Never create synthetic values — if data is missing, mark DATA UNAVAILABLE.",
  "Never assume missing data — reduce confidence and abstain when inputs are absent.",
  "Every output must cite its data source with timestamp and freshness.",
  "Every score must be reproducible via /api/gate/evaluate and /api/meridian/intelligence.",
  "Risk overrides opportunity — liquidity and regime vetoes beat momentum.",
  "No single skill may dominate — Constitution Engine aggregates weighted evidence.",
  "Disagreement is healthy — Bull and Bear courts must both be visible.",
  "Uncertainty must be visible — show spread, dissent, and data gaps.",
  "If data quality is low, abstain — prefer WAIT over fake certainty.",
  "Never hide failures — publish win rate, drawdown, and losing trades.",
  "Confidence is evidence strength — not probability of profit.",
] as const;

/** Never simplify by subtraction — reorganize complexity instead */
export const MERIDIAN_DO_NOT_DELETE = [
  "Never remove features — reorganize with progressive disclosure",
  "Never remove intelligence — surface summaries first, depth on expand",
  "Never reduce capabilities — preserve 100% of MERIDIAN depth",
  "Organize complexity — do not destroy it",
] as const;

export const MERIDIAN_DESIGN_TENETS = [
  "Powerful underneath, calm on the surface",
  "Complexity is acceptable — chaos is not",
  "Depth is acceptable — confusion is not",
  "One question per card — answers first, mechanics last",
  "Avoid button clutter and developer-dashboard aesthetics",
] as const;

export const MERIDIAN_VISUAL_HIERARCHY = {
  primary: ["Evidence direction", "Long / Short / Uncertainty scores", "Conviction", "Risk", "Thesis"],
  secondary: ["Bull vs Bear Court", "Constitution permit", "Narratives", "Market Memory"],
  tertiary: ["Indicators", "Metrics", "Raw calculations", "Research", "Weights"],
} as const;

export const MERIDIAN_UX_GOALS = [
  "I understand what is happening",
  "I know why the system thinks this",
  "I trust the output",
  "I can go deeper if I want",
  "I am never overwhelmed",
] as const;

export const MERIDIAN_ULTIMATE_GOAL =
  "Premium market intelligence OS — preserve intelligence, capabilities, and trust; optimize architecture, not features." as const;

export const MERIDIAN_INSPIRATION = [
  "Apple",
  "CoinMarketCap",
  "Bloomberg",
  "Stripe",
  "Linear",
  "Arc Browser",
  "TradingView",
  "Notion",
  "Palantir",
] as const;

export const MERIDIAN_CORE_PHILOSOPHY = {
  tagline: MERIDIAN_TAGLINE,
  northStar: MERIDIAN_NORTH_STAR,
  primaryObjective: MERIDIAN_PRIMARY_OBJECTIVE,
  trustHorizon: MERIDIAN_TRUST_HORIZON,
  dataLayer: "CoinMarketCap APIs provide raw materials only.",
  skillLayer: "Skills are deterministic calculators — evidence only, never BUY/SELL.",
  reasoningLayer: "Bull Court, Bear Court, and Constitution provide judgment.",
  memoryLayer: "Historical analogs are references, not predictions.",
  llmPlacement: "LLM sits near the end for narration — never at the beginning for numbers.",
  confidenceModel:
    "Confidence is evidence-derived (conviction, similarity, spread, completeness) — not probability of profit.",
  abstention: "If evidence conflicts or data is insufficient, output WAIT, FLAT, or UNKNOWN.",
  signalPhilosophy: MERIDIAN_SIGNAL_PHILOSOPHY,
  decisionEngine: MERIDIAN_DECISION_ENGINE,
  automation: "Agents enforce discipline — capital preservation, not trade count.",
  accountability: "Every closed trade gets autopsy; statistics are public including losses.",
  truthLaw: MERIDIAN_TRUTH_LAW,
} as const;

export const MERIDIAN_EXPLAINABILITY_QUESTIONS = [
  "Why?",
  "Why now?",
  "Why this asset?",
  "Who disagrees?",
  "What breaks the thesis?",
  "What conditions invalidate the trade?",
  "How long does the thesis remain valid?",
  "Have we seen this before?",
  "What historical situations resemble this?",
] as const;

export const MERIDIAN_DAILY_VALUE_LOOP = {
  morning: ["Market brief", "Narrative rotation", "Bull vs Bear Court", "Market Twin"],
  duringDay: ["Opportunity updates", "Constitution changes", "Counterfactual scenarios"],
  afterTrades: ["Trade autopsy", "Journal statistics", "Performance review"],
} as const;

export const MERIDIAN_USER_VOICE = [
  "MERIDIAN helps me think",
  "MERIDIAN explains itself",
  "MERIDIAN protects me from bad decisions",
  "MERIDIAN admits uncertainty",
  "MERIDIAN behaves like a disciplined professional",
] as const;

/** Instructions for any LLM touching MERIDIAN surfaces */
export const MERIDIAN_LLM_GUARDRAILS = [
  "Do not invent prices, RSI, Fear & Greed, volume, or conviction scores.",
  "Do not output BUY or SELL from skill logic — skills provide evidence only.",
  "Do not claim probability of profit — use conviction and evidence completeness.",
  "Do not claim 95% or 99% accuracy — a 70% win rate with risk management is exceptional.",
  "Do not smooth over missing data — say DATA UNAVAILABLE explicitly.",
  "Do not force agreement between Bull and Bear — show both sides.",
  "Do not mutate constitution rules automatically — suggest improvements only.",
  "Do not hide losses, drawdowns, or failed trades.",
  "Prefer WAIT over optimistic language when evidence is thin.",
  "Cite CoinMarketCap or skill name for every numeric claim.",
  "Cosmetic intelligence is forbidden — never invent value for appearance.",
  "Placeholder reasoning is forbidden — cite skills, APIs, or mark unavailable.",
] as const;

/** Track 2 Priority Mode — Gate product posture for BNB Hack judges */
export const MERIDIAN_TRACK2_PRIORITY = {
  flag: "NEXT_PUBLIC_MERIDIAN_TRACK2_PRIORITY",
  enabledValue: "1",
  gateIsPrimary: "Gate = CMC Strategy Skill product surface.",
  executionSecondary: "Execution is secondary. Strategy intelligence is primary.",
  overviewOneTruth: "Overview = router ONE TRUTH. Sub-tabs explain. Never compete.",
  multiTimeframeHonesty: "Multi-TF: different horizons, different truths — honest sources only.",
  walletPrinciple: "Wallets carry intelligence; they never own it.",
} as const;

/** Canonical master principles — see docs/MERIDIAN-MASTER-PRINCIPLES.md */
export const MERIDIAN_MASTER_PRINCIPLES = {
  identity: MERIDIAN_TAGLINE,
  northStar: MERIDIAN_NORTH_STAR,
  trustHorizon: MERIDIAN_TRUST_HORIZON,
  doNotDelete: MERIDIAN_DO_NOT_DELETE,
  designTenets: MERIDIAN_DESIGN_TENETS,
  visualHierarchy: MERIDIAN_VISUAL_HIERARCHY,
  uxGoals: MERIDIAN_UX_GOALS,
  ultimateGoal: MERIDIAN_ULTIMATE_GOAL,
  qualityRules: MERIDIAN_QUALITY_RULES,
  signalPhilosophy: MERIDIAN_SIGNAL_PHILOSOPHY,
  decisionEngine: MERIDIAN_DECISION_ENGINE,
  goldenRules: MERIDIAN_GOLDEN_RULES,
  truthLaw: MERIDIAN_TRUTH_LAW,
  truthForbidden: MERIDIAN_TRUTH_FORBIDDEN,
  truthRequirements: MERIDIAN_TRUTH_REQUIREMENTS,
  track2Priority: MERIDIAN_TRACK2_PRIORITY,
} as const;

/** Payload philosophy block — shipped to clients */
export const MERIDIAN_PHILOSOPHY_BULLETS = [
  MERIDIAN_NORTH_STAR,
  MERIDIAN_TRUST_HORIZON,
  ...MERIDIAN_QUALITY_RULES.slice(0, 3),
] as const;

export function resolveMeridianVerdict(input: {
  permitStatus?: "GRANT" | "DENY";
  dataQuality: MeridianDataQuality;
  hasConsensus: boolean;
}): MeridianVerdict {
  if (input.dataQuality === "unavailable") return "UNKNOWN";
  if (input.dataQuality === "degraded" && !input.hasConsensus) return "WAIT";
  if (input.dataQuality === "partial" && !input.hasConsensus) return "WAIT";
  if (!input.hasConsensus) return "WAIT";
  if (input.permitStatus === "GRANT") return "GRANT";
  if (input.permitStatus === "DENY") return "DENY";
  return "WAIT";
}

export function assessDataQuality(input: {
  cmcLive?: boolean;
  degraded?: boolean;
  fieldsPresent?: number;
  fieldsTotal?: number;
}): MeridianDataQuality {
  if (input.cmcLive === false && input.degraded) return "unavailable";
  if (input.cmcLive === false || input.degraded) return "degraded";
  const total = input.fieldsTotal ?? 0;
  const present = input.fieldsPresent ?? total;
  if (total > 0 && present / total < 0.6) return "partial";
  if (total > 0 && present / total < 0.85) return "partial";
  return "complete";
}
